# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: esp32_commander.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'esp32_commander.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x65sp32_commander.proto\"<\n\nMessageCmd\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08\x64uration\x18\x02 \x01(\x05\x12\x0e\n\x06scroll\x18\x03 \x01(\x08\"\\\n\x06LedCmd\x12\r\n\x05state\x18\x01 \x01(\x08\x12\x12\n\nbrightness\x18\x02 \x01(\x05\x12\t\n\x01r\x18\x03 \x01(\x05\x12\t\n\x01g\x18\x04 \x01(\x05\x12\t\n\x01\x62\x18\x05 \x01(\x05\x12\x0e\n\x06\x65\x66\x66\x65\x63t\x18\x06 \x01(\t\"T\n\tHapticCmd\x12\x0f\n\x07pattern\x18\x01 \x01(\t\x12\x11\n\tintensity\x18\x02 \x01(\x05\x12\x13\n\x0b\x64uration_ms\x18\x03 \x01(\x05\x12\x0e\n\x06repeat\x18\x04 \x01(\x05\"\x1e\n\x06RawCmd\x12\x14\n\x0cpayload_json\x18\x01 \x01(\t\"\xa3\x01\n\tStatusMsg\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x10\n\x08\x66irmware\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\x0c\n\x04rssi\x18\x04 \x01(\x11\x12\x0e\n\x06uptime\x18\x05 \x01(\x05\x12\x11\n\tfree_heap\x18\x06 \x01(\x05\x12\x11\n\tled_state\x18\x07 \x01(\x08\x12\x11\n\ttimestamp\x18\x08 \x01(\x03\x12\x0e\n\x06online\x18\t \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'esp32_commander_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGECMD']._serialized_start=25
  _globals['_MESSAGECMD']._serialized_end=85
  _globals['_LEDCMD']._serialized_start=87
  _globals['_LEDCMD']._serialized_end=179
  _globals['_HAPTICCMD']._serialized_start=181
  _globals['_HAPTICCMD']._serialized_end=265
  _globals['_RAWCMD']._serialized_start=267
  _globals['_RAWCMD']._serialized_end=297
  _globals['_STATUSMSG']._serialized_start=300
  _globals['_STATUSMSG']._serialized_end=463
# @@protoc_insertion_point(module_scope)
