/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "esp32_commander.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MessageCmd, MessageCmd, AUTO)


PB_BIND(LedCmd, LedCmd, AUTO)


PB_BIND(HapticCmd, HapticCmd, AUTO)


PB_BIND(RawCmd, RawCmd, 2)


PB_BIND(StatusMsg, StatusMsg, AUTO)



