/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ESP32_COMMANDER_PB_H_INCLUDED
#define PB_ESP32_COMMANDER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* esp32/{device_id}/cmd/message */
typedef struct _MessageCmd {
    char text[128]; /* Text to display */
    int32_t duration; /* Display duration in seconds */
    bool scroll; /* Whether to scroll long text */
} MessageCmd;

/* esp32/{device_id}/cmd/led */
typedef struct _LedCmd {
    bool state; /* true = on, false = off */
    int32_t brightness; /* 0–255 */
    int32_t r; /* Red channel 0–255 */
    int32_t g; /* Green channel 0–255 */
    int32_t b; /* Blue channel 0–255 */
    char effect[32]; /* solid | blink | pulse | rainbow */
} LedCmd;

/* esp32/{device_id}/cmd/haptic */
typedef struct _HapticCmd {
    char pattern[32]; /* short | long | double | sos | custom */
    int32_t intensity; /* 0–255 motor drive strength */
    int32_t duration_ms; /* Single pulse length in ms (used by custom) */
    int32_t repeat; /* Number of times to repeat the pattern */
} HapticCmd;

/* esp32/{device_id}/cmd/{any other action}
 payload_json carries an arbitrary JSON string for extensibility */
typedef struct _RawCmd {
    char payload_json[512];
} RawCmd;

/* esp32/{device_id}/status  (retained=true)
 An empty/zero message (online=false, device_id="") is used as the LWT
 to signal that the device has disconnected. */
typedef struct _StatusMsg {
    char device_id[32];
    char firmware[16];
    char ip[16];
    int32_t rssi; /* Typically negative; sint32 uses zigzag encoding for efficiency */
    int32_t uptime; /* Seconds since boot */
    int32_t free_heap; /* Free heap bytes */
    bool led_state;
    int64_t timestamp; /* millis() at publish time */
    bool online; /* true = device is up; false (default) = LWT / offline */
} StatusMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define MessageCmd_init_default                  {"", 0, 0}
#define LedCmd_init_default                      {0, 0, 0, 0, 0, ""}
#define HapticCmd_init_default                   {"", 0, 0, 0}
#define RawCmd_init_default                      {""}
#define StatusMsg_init_default                   {"", "", "", 0, 0, 0, 0, 0, 0}
#define MessageCmd_init_zero                     {"", 0, 0}
#define LedCmd_init_zero                         {0, 0, 0, 0, 0, ""}
#define HapticCmd_init_zero                      {"", 0, 0, 0}
#define RawCmd_init_zero                         {""}
#define StatusMsg_init_zero                      {"", "", "", 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define MessageCmd_text_tag                      1
#define MessageCmd_duration_tag                  2
#define MessageCmd_scroll_tag                    3
#define LedCmd_state_tag                         1
#define LedCmd_brightness_tag                    2
#define LedCmd_r_tag                             3
#define LedCmd_g_tag                             4
#define LedCmd_b_tag                             5
#define LedCmd_effect_tag                        6
#define HapticCmd_pattern_tag                    1
#define HapticCmd_intensity_tag                  2
#define HapticCmd_duration_ms_tag                3
#define HapticCmd_repeat_tag                     4
#define RawCmd_payload_json_tag                  1
#define StatusMsg_device_id_tag                  1
#define StatusMsg_firmware_tag                   2
#define StatusMsg_ip_tag                         3
#define StatusMsg_rssi_tag                       4
#define StatusMsg_uptime_tag                     5
#define StatusMsg_free_heap_tag                  6
#define StatusMsg_led_state_tag                  7
#define StatusMsg_timestamp_tag                  8
#define StatusMsg_online_tag                     9

/* Struct field encoding specification for nanopb */
#define MessageCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   text,              1) \
X(a, STATIC,   SINGULAR, INT32,    duration,          2) \
X(a, STATIC,   SINGULAR, BOOL,     scroll,            3)
#define MessageCmd_CALLBACK NULL
#define MessageCmd_DEFAULT NULL

#define LedCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     state,             1) \
X(a, STATIC,   SINGULAR, INT32,    brightness,        2) \
X(a, STATIC,   SINGULAR, INT32,    r,                 3) \
X(a, STATIC,   SINGULAR, INT32,    g,                 4) \
X(a, STATIC,   SINGULAR, INT32,    b,                 5) \
X(a, STATIC,   SINGULAR, STRING,   effect,            6)
#define LedCmd_CALLBACK NULL
#define LedCmd_DEFAULT NULL

#define HapticCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   pattern,           1) \
X(a, STATIC,   SINGULAR, INT32,    intensity,         2) \
X(a, STATIC,   SINGULAR, INT32,    duration_ms,       3) \
X(a, STATIC,   SINGULAR, INT32,    repeat,            4)
#define HapticCmd_CALLBACK NULL
#define HapticCmd_DEFAULT NULL

#define RawCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   payload_json,      1)
#define RawCmd_CALLBACK NULL
#define RawCmd_DEFAULT NULL

#define StatusMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         1) \
X(a, STATIC,   SINGULAR, STRING,   firmware,          2) \
X(a, STATIC,   SINGULAR, STRING,   ip,                3) \
X(a, STATIC,   SINGULAR, SINT32,   rssi,              4) \
X(a, STATIC,   SINGULAR, INT32,    uptime,            5) \
X(a, STATIC,   SINGULAR, INT32,    free_heap,         6) \
X(a, STATIC,   SINGULAR, BOOL,     led_state,         7) \
X(a, STATIC,   SINGULAR, INT64,    timestamp,         8) \
X(a, STATIC,   SINGULAR, BOOL,     online,            9)
#define StatusMsg_CALLBACK NULL
#define StatusMsg_DEFAULT NULL

extern const pb_msgdesc_t MessageCmd_msg;
extern const pb_msgdesc_t LedCmd_msg;
extern const pb_msgdesc_t HapticCmd_msg;
extern const pb_msgdesc_t RawCmd_msg;
extern const pb_msgdesc_t StatusMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MessageCmd_fields &MessageCmd_msg
#define LedCmd_fields &LedCmd_msg
#define HapticCmd_fields &HapticCmd_msg
#define RawCmd_fields &RawCmd_msg
#define StatusMsg_fields &StatusMsg_msg

/* Maximum encoded size of messages (where known) */
#define ESP32_COMMANDER_PB_H_MAX_SIZE            RawCmd_size
#define HapticCmd_size                           66
#define LedCmd_size                              79
#define MessageCmd_size                          143
#define RawCmd_size                              514
#define StatusMsg_size                           110

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
